#!/bin/sh

# Config variables for versions and paths.

STOW_VERSION="2.4.1"
STOW_PACKAGE="stow-$STOW_VERSION"
STOW_PKG_PATH="$PKG_DIR/$STOW_PACKAGE"

NODE_VERSION="23.11.0"
NODE_PACKAGE="node-v$NODE_VERSION-linux-arm64"
NODE_PKG_PATH="$PKG_DIR/$NODE_PACKAGE"

PYTHON_VERSION="3.13.3"
PYTHON_PACKAGE="Python-$PYTHON_VERSION"
PYTHON_PKG_PATH="$PKG_DIR/$PYTHON_PACKAGE"

GETTEXT_VERSION="0.24"
GETTEXT_PACKAGE="gettext-$GETTEXT_VERSION"
GETTEXT_PKG_PATH="$PKG_DIR/$GETTEXT_PACKAGE"

NEOVIM_VERSION="0.11.1"
NEOVIM_PACKAGE="neovim-$NEOVIM_VERSION"
NEOVIM_PKG_PATH="$PKG_DIR/$NEOVIM_PACKAGE"
NEOVIM_DL="nvim-linux-arm64"

RIPGREP_VERSION="14.1.1"
RIPGREP_PACKAGE="ripgrep-$RIPGREP_VERSION-aarch64-unknown-linux-gnu"
RIPGREP_PKG_PATH="$PKG_DIR/$RIPGREP_PACKAGE"

GO_VERSION="1.24.2"
GO_PACKAGE="go$GO_VERSION.linux-arm64"
GO_PKG_PATH="$PKG_DIR/$GO_PACKAGE"
