#!/bin/sh

# Config variables for versions and paths.

NODE_VERSION="23.11.0"
NODE_PACKAGE="node-v$NODE_VERSION-linux-arm64"
NODE_PKG_PATH="$PKG_DIR/$NODE_PACKAGE"

NEOVIM_VERSION="0.11.1"
NEOVIM_PACKAGE="neovim-$NEOVIM_VERSION"
NEOVIM_PKG_PATH="$PKG_DIR/$NEOVIM_PACKAGE"
NEOVIM_DL="nvim-linux-arm64"

RIPGREP_VERSION="14.1.1"
RIPGREP_PACKAGE="ripgrep-$RIPGREP_VERSION-aarch64-unknown-linux-gnu"
RIPGREP_PKG_PATH="$PKG_DIR/$RIPGREP_PACKAGE"

GO_VERSION="1.24.2"
GO_PACKAGE="go$GO_VERSION.linux-arm64"
GO_PKG_PATH="$PKG_DIR/$GO_PACKAGE"

PYTHON_VERSION="3.13.3"
PYTHON_PACKAGE="python-static-aarch64-linux-musl"
PYTHON_PKG_PATH="$PKG_DIR/$PYTHON_PACKAGE"
