#!/bin/sh

STOW_VERSION="2.4.1"
STOW_PACKAGE="stow-$STOW_VERSION"
STOW_PKG_PATH="$PKG_DIR/$STOW_PACKAGE"

PYTHON_VERSION="3.13.3"
PYTHON_PACKAGE="Python-$PYTHON_VERSION"
PYTHON_PKG_PATH="$PKG_DIR/$PYTHON_PACKAGE"

GETTEXT_VERSION="0.24"
GETTEXT_PACKAGE="gettext-$GETTEXT_VERSION"
GETTEXT_PKG_PATH="$PKG_DIR/$GETTEXT_PACKAGE"
