#!/bin/sh

STOW_VERSION="2.4.1"
STOW_PACKAGE="stow-$STOW_VERSION"
STOW_PKG_PATH="$PKG_DIR/$STOW_PACKAGE"

GETTEXT_VERSION="0.24"
GETTEXT_PACKAGE="gettext-$GETTEXT_VERSION"
GETTEXT_PKG_PATH="$PKG_DIR/$GETTEXT_PACKAGE"
