#!/bin/sh

# Config variables for versions and paths.

NODE_VERSION="24.13.0"
NODE_PACKAGE="node-v$NODE_VERSION-linux-x64"
NODE_PKG_PATH="$PKG_DIR/$NODE_PACKAGE"

NEOVIM_VERSION="0.11.6"
NEOVIM_PACKAGE="neovim-$NEOVIM_VERSION"
NEOVIM_PKG_PATH="$PKG_DIR/$NEOVIM_PACKAGE"
NEOVIM_DL="nvim-linux-x86_64"

RIPGREP_VERSION="15.1.0"
RIPGREP_PACKAGE="ripgrep-$RIPGREP_VERSION-x86_64-unknown-linux-musl"
RIPGREP_PKG_PATH="$PKG_DIR/$RIPGREP_PACKAGE"

GO_VERSION="1.25.7"
GO_PACKAGE="go$GO_VERSION.linux-amd64"
GO_PKG_PATH="$PKG_DIR/$GO_PACKAGE"

PYTHON_VERSION="3.13.3"
PYTHON_PACKAGE="python-static-x86_64-linux-musl"
PYTHON_PKG_PATH="$PKG_DIR/$PYTHON_PACKAGE"

ZIG_VERSION="0.15.2"
ZIG_PACKAGE="zig-x86_64-linux-$ZIG_VERSION"
ZIG_PKG_PATH="$PKG_DIR/$ZIG_PACKAGE"
