#!/bin/sh

# Config variables for versions and paths.

NODE_VERSION="23.11.0"
NODE_PACKAGE="node-v$NODE_VERSION-linux-x64"
NODE_PKG_PATH="$PKG_DIR/$NODE_PACKAGE"

NEOVIM_VERSION="0.11.1"
NEOVIM_PACKAGE="neovim-$NEOVIM_VERSION"
NEOVIM_PKG_PATH="$PKG_DIR/$NEOVIM_PACKAGE"
NEOVIM_DL="nvim-linux-x86_64"

RIPGREP_VERSION="14.1.1"
RIPGREP_PACKAGE="ripgrep-$RIPGREP_VERSION-x86_64-unknown-linux-musl"
RIPGREP_PKG_PATH="$PKG_DIR/$RIPGREP_PACKAGE"

GO_VERSION="1.24.2"
GO_PACKAGE="go$GO_VERSION.linux-amd64"
GO_PKG_PATH="$PKG_DIR/$GO_PACKAGE"
